import type { IconType } from "react-icons";
import {
  FiUsers,
  FiShare2,
  FiAward,
  FiMonitor,
  FiWind,
  FiCast,
  FiBookOpen,
  FiCreditCard,
  FiCompass,
  FiBriefcase,
  FiHeart,
  FiWifi,
  FiCheckSquare,
  FiDroplet,
  FiHome,
  FiUserCheck,
  FiShield,
  FiClock,
  FiFileText,
  FiLayout,
  FiTrendingUp,
  FiGrid,
  FiCode,
  FiLayers,
  FiZap,
  FiCode as FiCode2,
  FiFeather,
  FiDatabase,
  FiServer,
  FiTerminal,
  FiCpu,
  FiGlobe,
  FiPenTool,
  FiBox,
  FiPhone,
  FiMail,
  FiMapPin,
  FiArrowRight,
  FiPlus,
  FiStar,
  FiChevronLeft,
  FiChevronRight,
  FiX,
  FiMenu,
  FiCheckCircle,
  FiChevronUp,
} from "react-icons/fi";
import { FaWhatsapp, FaRupeeSign } from "react-icons/fa";

/**
 * Central icon registry. Constants/seed data reference icons by a
 * string key (e.g. "monitor") so the same key can be stored in the
 * database and safely mapped to a concrete component here — keeping
 * the data layer free of JSX.
 */
export const ICONS: Record<string, IconType> = {
  users: FiUsers,
  network: FiShare2,
  certificate: FiAward,
  monitor2: FiCast,
  snowflake: FiWind,
  presentation: FiCast,
  bookOpen: FiBookOpen,
  wallet: FiCreditCard,
  compass: FiCompass,
  briefcase2: FiBriefcase,
  laptop: FiMonitor,
  heart: FiHeart,
  wifi: FiWifi,
  checkFile: FiCheckSquare,
  droplet: FiDroplet,
  washroom: FiHome,
  users2: FiUserCheck,
  userGroup: FiUsers,
  shield: FiShield,
  clock: FiClock,
  monitor: FiMonitor,
  award: FiAward,
  fileText: FiFileText,
  layout: FiLayout,
  trendingUp: FiTrendingUp,
  briefcase: FiBriefcase,
  grid: FiGrid,
  rupee: FaRupeeSign,
  code: FiCode,
  layers: FiLayers,
  zap: FiZap,
  code2: FiCode2,
  palette: FiFeather,
  database: FiDatabase,
  database2: FiServer,
  terminal: FiTerminal,
  terminal2: FiCpu,
  globe: FiGlobe,
  drafting: FiPenTool,
  cube: FiBox,
  phone: FiPhone,
  mail: FiMail,
  mapPin: FiMapPin,
  whatsapp: FaWhatsapp,
  arrowRight: FiArrowRight,
  plus: FiPlus,
  star: FiStar,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  close: FiX,
  menu: FiMenu,
  checkCircle: FiCheckCircle,
  chevronUp: FiChevronUp,
};

export const getIcon = (key: string): IconType => ICONS[key] || FiCheckCircle;
