/**
 * Seed data for the Question Bank — 10 categories x 15 real MCQs each.
 * This is initial/starter content only; in production all questions
 * are created/imported dynamically via the Admin Panel, never hardcoded
 * into the exam engine itself.
 */
export const CATEGORIES = [
  "Computer Fundamentals",
  "MS Word",
  "MS Excel",
  "Microsoft PowerPoint",
  "Internet",
  "Windows Operating System",
  "Computer Hardware",
  "Computer Software",
  "Computer Networking",
  "Cyber Security",
];

const Q = (question, options, correctAnswer, difficulty = "Medium") => ({
  question,
  optionA: options[0],
  optionB: options[1],
  optionC: options[2],
  optionD: options[3],
  correctAnswer,
  difficulty,
  marks: 1,
});

export const QUESTIONS_BY_CATEGORY = {
  "Computer Fundamentals": [
    Q("What does CPU stand for?", ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Control Processing Unit"], "A", "Easy"),
    Q("Which of these is an input device?", ["Monitor", "Printer", "Keyboard", "Speaker"], "C", "Easy"),
    Q("1 Byte is equal to how many bits?", ["4", "8", "16", "32"], "B", "Easy"),
    Q("Which unit measures computer processing speed?", ["Hertz", "Watts", "Volts", "Bytes"], "A", "Medium"),
    Q("RAM is a type of ___ memory.", ["Permanent", "Volatile", "Secondary", "Optical"], "B", "Medium"),
    Q("Which of the following is an output device?", ["Mouse", "Scanner", "Monitor", "Keyboard"], "C", "Easy"),
    Q("What does ALU stand for in a CPU?", ["Arithmetic Logic Unit", "Array Logic Unit", "Automatic Logic Unit", "Arithmetic Level Unit"], "A", "Hard"),
    Q("Which generation of computers used transistors?", ["First", "Second", "Third", "Fourth"], "B", "Hard"),
    Q("A byte is made up of how many bits?", ["2", "4", "8", "16"], "C", "Easy"),
    Q("Which of these is the smallest unit of data?", ["Byte", "Bit", "Nibble", "Kilobyte"], "B", "Easy"),
    Q("What does GUI stand for?", ["Graphical User Interface", "General User Interface", "Graphic Utility Interface", "General Utility Interface"], "A", "Medium"),
    Q("Which memory is non-volatile?", ["RAM", "Cache", "ROM", "Register"], "C", "Medium"),
    Q("What is the full form of ICT?", ["Information and Communication Technology", "Internet Communication Tool", "Information Computer Technology", "Integrated Communication Technology"], "A", "Medium"),
    Q("Which part of the computer is called the 'brain'?", ["Monitor", "CPU", "Keyboard", "Hard Disk"], "B", "Easy"),
    Q("Which of these is a pointing device?", ["Mouse", "Keyboard", "Printer", "Scanner"], "A", "Easy"),
  ],
  "MS Word": [
    Q("Which extension is used for a default Word document?", [".txt", ".docx", ".xlsx", ".pptx"], "B", "Easy"),
    Q("Which tab contains the 'Font' group in MS Word?", ["Insert", "Home", "View", "References"], "B", "Easy"),
    Q("What is the shortcut key for Bold text?", ["Ctrl+B", "Ctrl+I", "Ctrl+U", "Ctrl+P"], "A", "Easy"),
    Q("Which feature checks spelling and grammar?", ["Find & Replace", "Spelling & Grammar", "Word Count", "Track Changes"], "B", "Easy"),
    Q("What is the shortcut for 'Find and Replace'?", ["Ctrl+F", "Ctrl+H", "Ctrl+R", "Ctrl+E"], "B", "Medium"),
    Q("Which view shows a document as it will print?", ["Draft View", "Print Layout View", "Outline View", "Web Layout View"], "B", "Medium"),
    Q("Which key combination saves a Word document?", ["Ctrl+S", "Ctrl+D", "Ctrl+V", "Ctrl+N"], "A", "Easy"),
    Q("Mail Merge is used to create multiple ___.", ["Charts", "Personalized letters", "Tables", "Images"], "B", "Medium"),
    Q("Which tab has the 'Page Margins' option?", ["Home", "Insert", "Layout", "Review"], "C", "Medium"),
    Q("What does 'Ctrl+Z' do?", ["Redo", "Undo", "Copy", "Paste"], "B", "Easy"),
    Q("Which feature tracks edits made by multiple users?", ["AutoCorrect", "Track Changes", "Mail Merge", "Word Art"], "B", "Medium"),
    Q("How do you insert a table in Word?", ["Insert tab > Table", "Home tab > Table", "View tab > Table", "Layout tab > Table"], "A", "Easy"),
    Q("Which shortcut selects the entire document?", ["Ctrl+A", "Ctrl+S", "Ctrl+D", "Ctrl+E"], "A", "Easy"),
    Q("Header and Footer options are found under which tab?", ["Home", "Insert", "References", "Mailings"], "B", "Medium"),
    Q("What is the default font size in MS Word (recent versions)?", ["10", "11", "12", "14"], "B", "Hard"),
  ],
  "MS Excel": [
    Q("A worksheet is made up of rows and ___.", ["Charts", "Columns", "Tabs", "Sheets"], "B", "Easy"),
    Q("Which symbol starts a formula in Excel?", ["#", "@", "=", "$"], "C", "Easy"),
    Q("What does the SUM function do?", ["Multiplies numbers", "Adds numbers", "Finds average", "Counts cells"], "B", "Easy"),
    Q("Which key is used to edit a cell?", ["F1", "F2", "F5", "F9"], "B", "Medium"),
    Q("What does '$A$1' represent in a formula?", ["Relative reference", "Absolute reference", "Mixed reference", "Named range"], "B", "Hard"),
    Q("Which function finds the average of a range?", ["SUM", "AVERAGE", "COUNT", "MAX"], "B", "Easy"),
    Q("What is the intersection of a row and column called?", ["Field", "Cell", "Table", "Range"], "B", "Easy"),
    Q("Which chart type is best for showing trends over time?", ["Pie Chart", "Line Chart", "Bar Chart", "Column Chart"], "B", "Medium"),
    Q("Which function counts numeric cells in a range?", ["COUNT", "COUNTA", "SUM", "COUNTBLANK"], "A", "Medium"),
    Q("What is the file extension of an Excel workbook?", [".xlsx", ".docx", ".pptx", ".txt"], "A", "Easy"),
    Q("Which feature helps filter data based on conditions?", ["Sort", "AutoFilter", "Format Painter", "Freeze Panes"], "B", "Medium"),
    Q("The VLOOKUP function searches data in ___.", ["Rows", "Columns", "Charts", "Sheets"], "B", "Hard"),
    Q("Which shortcut key opens a new workbook?", ["Ctrl+N", "Ctrl+O", "Ctrl+S", "Ctrl+W"], "A", "Easy"),
    Q("What does 'Freeze Panes' do?", ["Deletes rows", "Keeps rows/columns visible while scrolling", "Merges cells", "Sorts data"], "B", "Medium"),
    Q("Which function returns the largest value in a range?", ["MIN", "MAX", "SUM", "AVERAGE"], "B", "Easy"),
  ],
  "Microsoft PowerPoint": [
    Q("A PowerPoint file is called a ___.", ["Document", "Presentation", "Worksheet", "Sheet"], "B", "Easy"),
    Q("Which view shows all slides as thumbnails?", ["Normal View", "Slide Sorter View", "Reading View", "Outline View"], "B", "Medium"),
    Q("Which key starts a slideshow from the beginning?", ["F5", "F2", "F7", "F10"], "A", "Easy"),
    Q("What is used to move from one slide to another with effects?", ["Animation", "Transition", "Template", "Layout"], "B", "Medium"),
    Q("Which tab is used to insert a new slide?", ["Home", "Design", "Insert", "Review"], "A", "Easy"),
    Q("What is the file extension of a PowerPoint presentation?", [".pptx", ".docx", ".xlsx", ".pdf"], "A", "Easy"),
    Q("Which feature applies motion to text and objects on a slide?", ["Transition", "Animation", "SmartArt", "Theme"], "B", "Medium"),
    Q("Slide Master is used to ___.", ["Print slides", "Apply consistent design across slides", "Add sound", "Delete slides"], "B", "Hard"),
    Q("Which shortcut ends a slideshow?", ["Esc", "F5", "Ctrl+E", "Alt+F4"], "A", "Easy"),
    Q("What is used to display data visually as charts in PowerPoint?", ["SmartArt", "WordArt", "Chart tool", "Animation"], "C", "Medium"),
    Q("Which panel shows speaker notes?", ["Slide Pane", "Notes Pane", "Outline Pane", "Task Pane"], "B", "Medium"),
    Q("Which option lets you set the time each slide appears?", ["Slide Timing", "Rehearse Timings", "Animation Timing", "Slide Duration"], "B", "Hard"),
    Q("What is a template in PowerPoint?", ["A saved design layout", "An animation type", "A chart type", "A sound file"], "A", "Easy"),
    Q("Which tab includes 'Transitions' options?", ["Home", "Design", "Transitions", "Insert"], "C", "Easy"),
    Q("What does SmartArt help create?", ["Diagrams and visual lists", "Sound effects", "Slide numbers", "Speaker notes"], "A", "Medium"),
  ],
  "Internet": [
    Q("What does WWW stand for?", ["World Wide Web", "World Wide Wire", "Web Wide World", "World Web Wire"], "A", "Easy"),
    Q("Which protocol is used to browse websites?", ["FTP", "HTTP", "SMTP", "POP3"], "B", "Easy"),
    Q("What is a web browser?", ["A search engine", "Software to access websites", "An email service", "A programming language"], "B", "Easy"),
    Q("Which symbol is used in an email address?", ["#", "@", "&", "%"], "B", "Easy"),
    Q("What does URL stand for?", ["Uniform Resource Locator", "Universal Resource Link", "Uniform Reference Locator", "United Resource Locator"], "A", "Medium"),
    Q("Which of these is a search engine?", ["Google", "MS Word", "Excel", "Windows"], "A", "Easy"),
    Q("What does ISP stand for?", ["Internet Service Provider", "Internal Service Provider", "Internet System Provider", "Integrated Service Provider"], "A", "Medium"),
    Q("HTTPS is more secure than HTTP because it uses ___.", ["Compression", "Encryption", "Caching", "Cookies"], "B", "Medium"),
    Q("What is used to download files from the internet using a dedicated protocol?", ["HTTP", "FTP", "SMTP", "TCP"], "B", "Hard"),
    Q("What is a 'cookie' in web browsing?", ["A virus", "A small data file stored by a website", "A type of browser", "An email attachment"], "B", "Medium"),
    Q("Which of these is a valid email service?", ["Gmail", "MS Excel", "Photoshop", "AutoCAD"], "A", "Easy"),
    Q("What does Wi-Fi allow?", ["Wired connection only", "Wireless internet connection", "Only local file sharing", "Printing documents"], "B", "Easy"),
    Q("A hyperlink is used to ___.", ["Format text", "Navigate to another page/resource", "Insert an image", "Change font size"], "B", "Easy"),
    Q("Which of these is a popular web browser?", ["Chrome", "Excel", "Access", "Notepad"], "A", "Easy"),
    Q("What is downloading?", ["Sending data to a server", "Receiving data from the internet to your device", "Deleting files", "Printing files"], "B", "Easy"),
  ],
  "Windows Operating System": [
    Q("What is the default file manager in Windows called?", ["File Explorer", "Finder", "Files", "Manager"], "A", "Easy"),
    Q("Which key combination opens Task Manager?", ["Ctrl+Shift+Esc", "Ctrl+Alt+Tab", "Alt+F4", "Ctrl+P"], "A", "Medium"),
    Q("What does the Recycle Bin store?", ["Installed programs", "Deleted files", "System files", "Downloaded files"], "B", "Easy"),
    Q("Which shortcut minimizes all open windows?", ["Windows+D", "Windows+E", "Windows+L", "Windows+R"], "A", "Medium"),
    Q("What is the taskbar used for?", ["Editing documents", "Accessing open apps and system tray", "Browsing the internet", "Formatting disks"], "B", "Easy"),
    Q("Which shortcut opens File Explorer?", ["Windows+E", "Windows+R", "Windows+D", "Windows+L"], "A", "Medium"),
    Q("What does 'Control Panel' allow you to do?", ["Play games", "Change system settings", "Browse the web", "Edit photos"], "B", "Easy"),
    Q("Which file system is commonly used by modern Windows?", ["FAT32", "NTFS", "EXT4", "HFS+"], "B", "Hard"),
    Q("What does Windows+L do?", ["Logs off", "Locks the computer", "Opens File Explorer", "Opens Run dialog"], "B", "Medium"),
    Q("What is 'Safe Mode' used for?", ["Faster gaming", "Troubleshooting startup problems", "Better graphics", "Internet browsing"], "B", "Hard"),
    Q("Which tool shows running processes and resource usage?", ["Task Manager", "File Explorer", "Control Panel", "Notepad"], "A", "Easy"),
    Q("What does 'Windows+R' open?", ["Run dialog", "Recycle Bin", "Registry", "Task Manager"], "A", "Medium"),
    Q("Which of these is a Windows operating system version?", ["Windows 11", "Ubuntu", "macOS", "Android"], "A", "Easy"),
    Q("What is the purpose of Disk Cleanup?", ["Formats the hard disk", "Frees up disk space by removing unneeded files", "Installs new software", "Partitions the disk"], "B", "Medium"),
    Q("Which shortcut switches between open applications?", ["Alt+Tab", "Ctrl+Tab", "Shift+Tab", "Windows+Tab"], "A", "Easy"),
  ],
  "Computer Hardware": [
    Q("Which of these is the main circuit board of a computer?", ["RAM", "Motherboard", "Hard Disk", "Power Supply"], "B", "Easy"),
    Q("Which device is used for permanent data storage?", ["RAM", "Cache", "Hard Disk", "Register"], "C", "Easy"),
    Q("What does SSD stand for?", ["Solid State Drive", "Secondary Storage Device", "System Storage Disk", "Solid Storage Disk"], "A", "Medium"),
    Q("Which port is commonly used to connect a monitor?", ["USB", "HDMI", "Ethernet", "PS/2"], "B", "Easy"),
    Q("What is the function of the power supply unit (PSU)?", ["Processes data", "Converts and supplies power to components", "Stores data", "Displays output"], "B", "Medium"),
    Q("Which of these is a type of printer?", ["Laser", "Optical", "Wireless", "Solid State"], "A", "Easy"),
    Q("What does GPU stand for?", ["General Processing Unit", "Graphics Processing Unit", "Global Processing Unit", "General Program Unit"], "B", "Medium"),
    Q("Which component cools down the CPU?", ["RAM", "Heat sink/Fan", "Hard Disk", "Motherboard"], "B", "Medium"),
    Q("Which cable type is commonly used for internet/network connection?", ["HDMI", "Ethernet", "VGA", "USB"], "B", "Easy"),
    Q("What is the function of RAM?", ["Permanent storage", "Temporary working memory", "Cooling the CPU", "Displaying output"], "B", "Medium"),
    Q("Which of these is an example of secondary storage?", ["RAM", "Cache", "Hard Disk", "Register"], "C", "Easy"),
    Q("What does DVD stand for?", ["Digital Versatile Disc", "Digital Video Device", "Data Video Disc", "Digital Visual Disc"], "A", "Medium"),
    Q("Which hardware component executes instructions?", ["CPU", "Monitor", "Keyboard", "Speaker"], "A", "Easy"),
    Q("Which of these connects wirelessly to a computer?", ["Bluetooth mouse", "Wired keyboard", "VGA cable", "Ethernet cable"], "A", "Easy"),
    Q("What is the function of a scanner?", ["Prints documents", "Converts physical documents into digital images", "Displays video", "Stores data permanently"], "B", "Medium"),
  ],
  "Computer Software": [
    Q("Which of these is system software?", ["MS Word", "Windows OS", "Photoshop", "Chrome"], "B", "Easy"),
    Q("What is application software used for?", ["Managing hardware only", "Performing specific user tasks", "Booting the computer", "Compiling code only"], "B", "Easy"),
    Q("Which of these is an example of an operating system?", ["Linux", "MS Excel", "AutoCAD", "Tally"], "A", "Easy"),
    Q("What is 'freeware'?", ["Software available free of cost", "Faulty software", "Software with a trial period only", "Hardware component"], "A", "Medium"),
    Q("Which type of software translates high-level code to machine code line-by-line?", ["Compiler", "Interpreter", "Assembler", "Linker"], "B", "Hard"),
    Q("Which of these is antivirus software?", ["Quick Heal", "MS Word", "Excel", "PowerPoint"], "A", "Easy"),
    Q("What is a compiler?", ["Converts entire source code to machine code at once", "Deletes files", "Formats disks", "Manages memory only"], "A", "Medium"),
    Q("Which category does a device driver belong to?", ["Application software", "System software", "Utility only", "Firmware only"], "B", "Hard"),
    Q("Which of these is utility software?", ["Disk Cleanup", "MS Word", "Photoshop", "Tally"], "A", "Medium"),
    Q("What does 'open-source software' mean?", ["Source code is publicly available", "Software is always free", "Only works offline", "Cannot be modified"], "A", "Medium"),
    Q("Which of these is a popular web browser software?", ["Google Chrome", "MS Excel", "Windows Media Player", "Notepad"], "A", "Easy"),
    Q("What is 'shareware'?", ["Fully free forever", "Trial software, often with limitations", "Only for businesses", "Illegal software"], "B", "Medium"),
    Q("Which of these is a programming language?", ["Python", "Windows", "Chrome", "PDF"], "A", "Easy"),
    Q("Firmware is typically stored in ___.", ["RAM", "ROM", "Cache", "Hard Disk"], "B", "Hard"),
    Q("Which of the following best describes 'malware'?", ["Useful productivity software", "Malicious software intended to harm systems", "A hardware component", "An operating system"], "B", "Easy"),
  ],
  "Computer Networking": [
    Q("What does LAN stand for?", ["Local Area Network", "Large Area Network", "Local Access Network", "Linked Area Network"], "A", "Easy"),
    Q("Which device connects multiple computers in a network?", ["Switch", "Monitor", "Keyboard", "Printer"], "A", "Easy"),
    Q("What does IP address stand for?", ["Internet Protocol address", "Internal Program address", "Internet Program address", "Integrated Protocol address"], "A", "Medium"),
    Q("What does WAN stand for?", ["Wide Area Network", "Wireless Area Network", "Wide Access Network", "Wired Area Network"], "A", "Easy"),
    Q("Which device is used to connect a LAN to the Internet?", ["Router", "Mouse", "Scanner", "Printer"], "A", "Medium"),
    Q("What is the function of a firewall?", ["Speeds up internet", "Filters and blocks unauthorized network access", "Stores data", "Prints documents"], "B", "Medium"),
    Q("Which topology connects all devices to a single central hub?", ["Star", "Bus", "Ring", "Mesh"], "A", "Medium"),
    Q("What does DNS stand for?", ["Domain Name System", "Data Network System", "Digital Naming Service", "Domain Network Server"], "A", "Hard"),
    Q("Which protocol is used for sending emails?", ["SMTP", "HTTP", "FTP", "DNS"], "A", "Hard"),
    Q("What is the purpose of a modem?", ["Converts digital signals to analog and back", "Stores files", "Displays graphics", "Prints documents"], "A", "Medium"),
    Q("Which of these is a wireless networking technology?", ["Wi-Fi", "Ethernet cable", "VGA cable", "HDMI cable"], "A", "Easy"),
    Q("What does 'bandwidth' refer to?", ["Physical size of cable", "Data transfer capacity of a network", "Number of computers", "Screen resolution"], "B", "Hard"),
    Q("A network confined to a small area like an office is called ___.", ["WAN", "LAN", "MAN", "PAN"], "B", "Easy"),
    Q("Which device amplifies network signals over long distances?", ["Repeater", "Mouse", "Monitor", "Keyboard"], "A", "Hard"),
    Q("What is the main function of a network switch?", ["Connect devices within a LAN and direct data traffic", "Browse the internet", "Store large files", "Scan documents"], "A", "Medium"),
  ],
  "Cyber Security": [
    Q("What is a computer virus?", ["A hardware fault", "A malicious program that can replicate and harm systems", "A type of printer", "A network cable"], "B", "Easy"),
    Q("What does 'phishing' refer to?", ["A networking protocol", "Tricking users into revealing sensitive information", "A type of hardware", "A programming language"], "B", "Medium"),
    Q("What is a strong password practice?", ["Using your name", "Using 'password123'", "Mixing letters, numbers, and symbols", "Using the same password everywhere"], "C", "Easy"),
    Q("What does a firewall primarily protect against?", ["Power failures", "Unauthorized network access", "Hardware wear and tear", "Software bugs"], "B", "Medium"),
    Q("What is 'malware'?", ["Beneficial software", "Malicious software designed to cause harm", "A hardware component", "A network protocol"], "B", "Easy"),
    Q("What does two-factor authentication add to login security?", ["Nothing extra", "A second verification step beyond password", "A faster login", "A larger password"], "B", "Medium"),
    Q("What is 'ransomware'?", ["Free antivirus software", "Malware that locks data until a ransom is paid", "A firewall type", "A backup tool"], "B", "Medium"),
    Q("Which of these helps protect against viruses?", ["Antivirus software", "Deleting the browser", "Turning off the monitor", "Using weak passwords"], "A", "Easy"),
    Q("What is 'social engineering' in cyber security?", ["A networking hardware term", "Manipulating people into revealing confidential information", "A programming technique", "A type of firewall"], "B", "Hard"),
    Q("Why should software be kept updated?", ["To use more storage", "To patch security vulnerabilities", "To slow down the computer", "It has no real benefit"], "B", "Medium"),
    Q("What is a VPN used for?", ["Speeding up hardware", "Creating a secure, encrypted network connection", "Printing documents", "Editing photos"], "B", "Hard"),
    Q("What should you do with suspicious email attachments?", ["Open them immediately", "Avoid opening and verify the sender", "Forward to everyone", "Reply with personal details"], "B", "Easy"),
    Q("What is 'spyware'?", ["Software that secretly monitors user activity", "A type of printer", "A hardware firewall", "An antivirus tool"], "A", "Medium"),
    Q("Which practice reduces cyber security risk on public Wi-Fi?", ["Online banking freely", "Using a VPN or avoiding sensitive transactions", "Sharing your password", "Disabling antivirus"], "B", "Medium"),
    Q("What does 'encryption' do to data?", ["Deletes it permanently", "Converts it into a coded form to prevent unauthorized access", "Compresses it for storage", "Prints it automatically"], "B", "Hard"),
  ],
};
